[experimental]

[display]
dataframes = "rich"
code_editor_font_size = 14
cell_output = "above"
theme = "dark"
default_width = "medium"

[ai]

[save]
autosave = "after_delay"
format_on_save = false
autosave_delay = 1000

[formatting]
line_length = 79

[package_management]
manager = "pip"

[server]
browser = "default"
follow_symlink = false

[completion]
copilot = false
activate_on_typing = true

[keymap]
preset = "default"
[keymap.overrides]

[runtime]
on_cell_change = "autorun"
auto_instantiate = true
auto_reload = "off"
